package id.kenang.core.data.ffmpeg

/**
 * Builds `subtitles.ass` from the narration text WITHOUT ASR (MASTER_PROMPT_04
 * §4.2): the text is split into ≤42-char lines and cue timings are distributed
 * proportionally to sentence lengths across the measured narration duration.
 *
 * Style per spec: bottom-center, classy white with soft shadow, no boxes;
 * higher safe-area margin on 9:16.
 */
object AssBuilder {

    const val MAX_LINE_CHARS = 42

    /** One subtitle cue: [startMs, endMs) showing [lines] (1–2 lines). */
    data class Cue(val startMs: Long, val endMs: Long, val lines: List<String>)

    /** Splits text into display lines of at most [maxChars], breaking on spaces. */
    fun splitLines(text: String, maxChars: Int = MAX_LINE_CHARS): List<String> {
        val words = text.trim().split(Regex("\\s+")).filter { it.isNotBlank() }
        val lines = mutableListOf<String>()
        var current = StringBuilder()
        for (word in words) {
            when {
                current.isEmpty() -> current.append(word.take(maxChars))
                current.length + 1 + word.length <= maxChars -> current.append(' ').append(word)
                else -> {
                    lines += current.toString()
                    current = StringBuilder(word.take(maxChars))
                }
            }
        }
        if (current.isNotEmpty()) lines += current.toString()
        return lines
    }

    /**
     * Sentence-proportional cue plan: each sentence gets a slice of
     * [totalDurationMs] proportional to its character count, then its lines are
     * grouped into cues of at most 2 lines, splitting the sentence slice
     * proportionally again by line length.
     */
    fun buildCues(narration: String, totalDurationMs: Long): List<Cue> {
        val sentences = narration.trim()
            .split(Regex("(?<=[.!?…])\\s+"))
            .map { it.trim() }
            .filter { it.isNotBlank() }
        if (sentences.isEmpty() || totalDurationMs <= 0) return emptyList()

        val totalChars = sentences.sumOf { it.length }.toDouble()
        val cues = mutableListOf<Cue>()
        var cursorMs = 0.0
        for (sentence in sentences) {
            val sentenceMs = totalDurationMs * (sentence.length / totalChars)
            val lines = splitLines(sentence)
            val groups = lines.chunked(2)
            val groupChars = groups.sumOf { g -> g.sumOf { it.length } }.toDouble().coerceAtLeast(1.0)
            var groupStart = cursorMs
            for (group in groups) {
                val groupMs = sentenceMs * (group.sumOf { it.length } / groupChars)
                cues += Cue(groupStart.toLong(), (groupStart + groupMs).toLong(), group)
                groupStart += groupMs
            }
            cursorMs += sentenceMs
        }
        // Snap the last cue to the exact end so rounding never truncates it.
        if (cues.isNotEmpty()) {
            val last = cues.removeAt(cues.lastIndex)
            cues += last.copy(endMs = totalDurationMs)
        }
        return cues
    }

    /** Renders the full .ass document for [ratio] ("9:16" | "16:9"). */
    fun build(narration: String, totalDurationMs: Long, ratio: String): String {
        val portrait = ratio == "9:16"
        val playResX = if (portrait) 1080 else 1920
        val playResY = if (portrait) 1920 else 1080
        // 9:16 sits higher above platform UI chrome (safe area).
        val marginV = if (portrait) 260 else 90
        val fontSize = if (portrait) 58 else 56

        val sb = StringBuilder()
        sb.appendLine("[Script Info]")
        sb.appendLine("; Generated by Kenang — narration-proportional timing (no ASR)")
        sb.appendLine("ScriptType: v4.00+")
        sb.appendLine("PlayResX: $playResX")
        sb.appendLine("PlayResY: $playResY")
        sb.appendLine("WrapStyle: 0")
        sb.appendLine("ScaledBorderAndShadow: yes")
        sb.appendLine()
        sb.appendLine("[V4+ Styles]")
        sb.appendLine(
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, " +
                "Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, " +
                "Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        )
        // White text, no box (BorderStyle=1, Outline=0), soft translucent shadow.
        sb.appendLine(
            "Style: Kenang,Arial,$fontSize,&H00FFFFFF,&H00FFFFFF,&H00000000,&H90000000," +
                "0,0,0,0,100,100,0,0,1,0,2,2,60,60,$marginV,1",
        )
        sb.appendLine()
        sb.appendLine("[Events]")
        sb.appendLine("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text")
        for (cue in buildCues(narration, totalDurationMs)) {
            val text = cue.lines.joinToString("\\N")
            sb.appendLine("Dialogue: 0,${ts(cue.startMs)},${ts(cue.endMs)},Kenang,,0,0,0,,$text")
        }
        return sb.toString()
    }

    /** ASS timestamp `h:mm:ss.cc`. */
    internal fun ts(ms: Long): String {
        val cs = (ms / 10) % 100
        val s = (ms / 1000) % 60
        val m = (ms / 60_000) % 60
        val h = ms / 3_600_000
        return "%d:%02d:%02d.%02d".format(h, m, s, cs)
    }
}
